document.addEventListener("DOMContentLoaded", function () {
    fetch("http://5.161.44.208:3000/api/data?timeFrame=7d&simulate=false")
        .then(response => response.json())
        .then(data => {
            console.log("API Data: ", data);
            // Update the chart
            updateChart(data.labels, data.supplyChange, data.cumulativeEthGenerated);

            // Update the ETH values
            document.getElementById("total-eth").innerText = data.currentEthTotal.toFixed(4);

            // Ensure contractBalance is a number
            const contractBalance = parseFloat(data.contractBalance);
            if (!isNaN(contractBalance)) {
                document.getElementById("eth-generated-djt").innerText = contractBalance.toFixed(4);
                const percentage = ((contractBalance / data.currentEthTotal) * 100).toFixed(0);
                document.getElementById("eth-percentage-value").innerText = `${percentage}%`;
            } else {
                console.error("contractBalance is not a valid number");
            }
        })
        .catch(error => console.error("Error fetching data: ", error));
});

function updateChart(labels, supplyChange, cumulativeEthGenerated) {
    Highcharts.chart('myChart', {
        chart: {
            type: 'line',
            backgroundColor: '#2C3E50',
        },
        title: {
            text: ''
        },
        xAxis: {
            categories: labels,
            labels: {
                style: {
                    color: '#ECF0F1'
                }
            }
        },
        yAxis: {
            title: {
                text: ''
            },
            labels: {
                style: {
                    color: '#ECF0F1'
                }
            }
        },
        series: [{
            name: 'Supply Change Over Time',
            data: supplyChange,
            color: 'rgba(75, 192, 192, 1)'
        }, {
            name: 'Cumulative ETH Generated by $DJT',
            data: cumulativeEthGenerated,
            color: 'rgba(255, 99, 132, 1)'
        }],
        legend: {
            itemStyle: {
                color: '#ECF0F1'
            }
        }
    });
}
